---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgBI7jOmrP+8h+zOxJsn9KJw0p5HsojSRy7v95qxoPtm9HO8abyaxUfBqNoRwjyI5fSKmgwFEeQBjGNV3libwJ4ofesdKDZT94y8qqe92MUZxDV3UkqWUbfkslzc3E8xENYQZuQX4Qo88mVAiZmqtVWIocnKQgB/XhH4zBv7KUjkieDV9HDooW1kUUDtU36sLevt8q6flp7BPJpEwM+SnvPp97BpEh2YbZvOjFEoufo1JzR+9ImpvjrlcPQmr8HDZn9lFGmgmLwZAifygU+WX6LWVv876sRZDMqGqu+hStbhy+i7otaVOtNGSMn3vU7Fq/kUrUu7ylp6P1fBOUaOVQ3wsV1UPNMOWZtwcqG4i3Fvp2PfGWa470GLqApmvCg+8oCIhYrZffi/J1VTLlYuH4p1qZlqbgGo/rBeAPFr+jwCVd8GCXlx91ZfJ29AopIHu+zEQYnSsMs3EiS3bDoP7lB1UNlJwmX48imIk835m5sgv1zHQmDbS10NimLD/irZ/0bl3XAo7pYljMhkWTdYGonqbgm/ym1nbCiFyFoNJleGMdrPFo4VBwva4dK6uf7raoJo4k5EdF8Byu5bzYhF07SM1fctRZLftGMpmq2YSqkCpWX1xHdCKK+ucbO+QShJwIlNBJw/O6/FRPkIFsfBgAsW4Ukn6wsjwRknzYuO0bS/1Nchq5t7hsfDBaKfPNLcjSHSK7TOSQ==
  template:
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: external-dns
