---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: testing
  namespace: external-dns
spec:
  endpoints:
  - dnsName: testing.k8s.example.org
    recordTTL: 180
    recordType: A
    targets:
    - 10.60.128.220
