apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  interval: 15m
  url: https://kubernetes.github.io/ingress-nginx
