apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opensearch
  namespace: flux-system
spec:
  interval: 15m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/opensearch