kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-path-storage-pvc
spec:
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
