---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-hostpath
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-hostpath-ssd1
spec:
  storageClassName: openebs-hostpath-ssd1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-hostpath-ceph
spec:
  storageClassName: openebs-hostpath-ceph
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
