apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-post-config-script
  namespace: logging
data:
  opensearch-post-config-job.sh: |-
    #!/bin/env sh
    curl -k -v -L -XPUT -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" "$OPENSEARCH_SERVER/_index_template/logs_template" -H 'Content-Type: application/json' -d'
    {
      "index_patterns": [
        "logs-*"
      ],
      "data_stream": {
        "timestamp_field": {
          "name": "@timestamp"
        }
      },
      "priority": 1,
      "template": {
        "settings": {
          "number_of_shards": 1,
          "number_of_replicas": 0
        }
      }
    }'

    curl -k -v -L -XPUT -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" "$OPENSEARCH_SERVER/_index_template/auditlogs_template" -H 'Content-Type: application/json' -d'
    {
      "index_patterns": [
        "auditlogs-*"
      ],
      "data_stream": {
        "timestamp_field": {
          "name": "@timestamp"
        }
      },
      "priority": 1,
      "template": {
        "settings": {
          "number_of_shards": 1,
          "number_of_replicas": 0
        }
      }
    }'

    curl -k -v -L -XPUT -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" "$OPENSEARCH_SERVER/_plugins/_ism/policies/default_datastream_policy" -H 'Content-Type: application/json' -d'
    {
      "policy": {
        "description": "logs datastream policy",
        "default_state": "hot",
        "states": [
          {
            "name": "hot",
            "actions": [
              {
                "rollover": {
                  "min_index_age": "1h"
                }
              }
            ],
            "transitions": [
              {
                "state_name": "delete",
                "conditions": {
                  "min_index_age": "2h"
                }
              }
            ]
          },
          {
            "name": "delete",
            "actions": [
              {
                "delete": {}
              }
            ],
            "transitions": []
          }
        ],
        "ism_template": [
          {
            "index_patterns": [
              "auditlogs-*",
              "logs-*"
            ],
            "priority": 200
          }
        ]
      }
    }'