apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-syslog
  namespace: logging
spec:
  chart:
    spec:
      chart: vector
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      version: 0.36.1
  interval: 15m
  timeout: 5m
  releaseName: vector-syslog

  values:
    role: Aggregator
    replicas: 1
    customConfig:
      data_dir: /var/lib/vector
      api:
        enabled: false
      sources:
        syslog:
          type: syslog
          address : 0.0.0.0:15514
          mode : tcp
          path: /vector/syslog/socket
      sinks:
        console:
          type: "console"
          inputs:
            - syslog
          encoding:
            codec : "json"
