apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-falco
  namespace: logging
spec:
  chart:
    spec:
      chart: vector
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      version: 0.36.1
  interval: 15m
  timeout: 5m
  releaseName: vector-falco

  values:
    role: Aggregator
    replicas: 1
    customConfig:
      data_dir: /var/lib/vector
      api:
        enabled: false
      sources:
        fluent_falco:
          type: fluent
          address : "0.0.0.0:24224"
      sinks:
        console:
          type: "console"
          inputs:
            - fluent_falco
          encoding:
            codec : "json"
        # opensearch:
        #   inputs:
        #     - fluent_falco
        #   type: elasticsearch
        #   healthcheck: true
        #   api_version: v7
        #   endpoints:
        #     - "https://opensearch-cluster-master.logging:9200"
        #   tls:
        #     verify_certificate: false
        #     verify_hostname: false
        #   mode: data_stream
        #   # index pattern: type-dataset-namespace
        #   data_stream:
        #     type: "auditlogs"
        #     namespace: 'falco'
        #     dataset: "k8s"
        #   auth:
        #     strategy: basic
        #     user: "admin"
        #     password: "myStrongPassword123@456"
        #   request:
        #     concurrency: adaptive


