apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: ingress-nginx

  values:
    defaultBackend:
      enabled: false
    controller:
      publishService:
        enabled: true
      kind: Deployment
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.10.161
