apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.2
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: ingress-nginx

  values:
    defaultBackend:
      enabled: false
    controller:
      publishService:
        enabled: true      
      kind: Deployment
      service:
        enabled: true
        ipFamilyPolicy: PreferDualStack
        ipFamilies: ["IPv6","IPv4"]
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: 192.168.10.161,2a01:cb0c:81d1:a8fb::1161
