apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 31.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: traefik

  values:
    deployment:
      kind: Deployment
      replicas: 2
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    service:
      enabled: true
      ipFamilyPolicy: PreferDualStack
      ipFamilies: ["IPv6","IPv4"]
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: 192.168.10.162,2a01:cb0c:81d1:a8fb::1162

