apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: coredns
spec:
  chart:
    spec:
      chart: coredns
      version: 1.28.2
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: coredns

  values:
    rbac:
      create: true      
    # CoreDNS as an external dns service
    isClusterService: false
    serviceType: "LoadBalancer"

    # Default zone is what Kubernetes recommends:
    # https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
    servers:
    - zones:
      - zone: .
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      # Required to query kubernetes API for data
      # - name: kubernetes
      #   parameters: cluster.local in-addr.arpa ip6.arpa
      #   configBlock: |-
      #     pods insecure
      #     fallthrough in-addr.arpa ip6.arpa
      #     ttl 30
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: etcd
        parameters: example.org
        configBlock: |-
          stubzones
          path /skydns
          endpoint http://etcd.etcd.svc.cluster.local:2379
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance

