kind: Pod
apiVersion: v1
metadata:
  name: dbench
spec:
  nodeSelector:
    openebs.io/engine: mayastor
  containers:
  - name: dbench
    image: openebs/perf-test:latest
    imagePullPolicy: IfNotPresent
    args:
      - sleep
      - "1000000"
    env:
      - name: DBENCH_TYPE
        value: detailed
      - name: FIO_SIZE
        value: 2G
      - name: FIO_DIRECT
        value: '1'
      - name: FIO_NUMJOBS
        value: '1'
      - name: FIO_OFFSET_INCREMENT
        value: 250M
      - name: FIO_IOENGINE
        value: libaio
      - name: OPTIONS
        value: ''
      - name: CUSTOM
        value: ''
    volumeMounts:
      - mountPath: "/volume/sda"
        name: sda
      - mountPath: "/volume/ssd1"
        name: ssd1
      - mountPath: "/volume/ceph"
        name: ceph
      - mountPath: "/volume/rep-1"
        name: replicated-1
      - mountPath: "/volume/rep-3"
        name: replicated-3
  restartPolicy: Never
  volumes:
    - name: sda
      persistentVolumeClaim:
        claimName: openebs-hostpath
    - name: ssd1
      persistentVolumeClaim:
        claimName: openebs-hostpath-ssd1
    - name: ceph
      persistentVolumeClaim:
        claimName: openebs-hostpath-ceph
    - name: replicated-1
      persistentVolumeClaim:
        claimName: openebs-mayastor-1
    - name: replicated-3
      persistentVolumeClaim:
        claimName: openebs-mayastor-3
