kind: Pod
apiVersion: v1
metadata:
  name: dbench
spec:
  nodeSelector:
    openebs.io/engine: mayastor
  containers:
  - name: dbench
    image: openebs/perf-test:latest
    imagePullPolicy: IfNotPresent
    args:
      - sleep
      - "1000000"
    env:
      - name: DBENCH_TYPE
        value: detailed
      - name: FIO_SIZE
        value: 1G
      - name: FIO_DIRECT
        value: '1'
      - name: FIO_NUMJOBS
        value: '1'
      - name: FIO_OFFSET_INCREMENT
        value: 250M
      - name: FIO_IOENGINE
        value: libaio
      - name: OPTIONS
        value: ''
      - name: CUSTOM
        value: ''
    volumeMounts:
      - mountPath: "/volume/local-thin"
        name: local-thin
      - mountPath: "/volume/ssd1"
        name: ssd1
      - mountPath: "/volume/ssd2"
        name: ssd2
      - mountPath: "/volume/ceph"
        name: ceph
      - mountPath: "/volume/rep-1-slow"
        name: rep-1-slow
      - mountPath: "/volume/rep-1-fast"
        name: rep-1-fast
      - mountPath: "/volume/rep-3-slow"
        name: rep-3-slow
      - mountPath: "/volume/rep-3-fast"
        name: rep-3-fast
  restartPolicy: Never
  volumes:
    - name: local-thin
      persistentVolumeClaim:
        claimName: openebs-hostpath-local-thin
    - name: ssd1
      persistentVolumeClaim:
        claimName: openebs-hostpath-ssd1
    - name: ssd2
      persistentVolumeClaim:
        claimName: openebs-hostpath-ssd2
    - name: ceph
      persistentVolumeClaim:
        claimName: openebs-hostpath-ceph
    - name: rep-1-slow
      persistentVolumeClaim:
        claimName: openebs-1-replica-slow
    - name: rep-1-fast
      persistentVolumeClaim:
        claimName: openebs-1-replica-fast
    - name: rep-3-slow
      persistentVolumeClaim:
        claimName: openebs-3-replica-slow
    - name: rep-3-fast
      persistentVolumeClaim:
        claimName: openebs-3-replica-fast
