apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules
  namespace: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
data:
  rules-custom.yaml: |-
    - macro: container_started
      condition: ((evt.type = container) or (spawned_process and proc.vpid=1))

    - rule: New container with tag latest
      desc: Detect if a new container with the tag "latest" is started
      condition: >
        container_started and container.image.tag="latest"
      output: A new container with the tag "latest" is started (container_id=%container.id container_image=%container.image.repository container_image_tag=%container.image.tag container_name=%container.name k8s_ns=%k8s.ns.name k8s_pod_name=%k8s.pod.name)
      priority: INFO
      tags: [container, invalid_tag]
