---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-1-replica-slow
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "1"
  poolAffinityTopologyLabel: |
    disk: slow
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-1-replica-fast
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "1"
  poolAffinityTopologyLabel: |
    disk: fast
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-3-replica-slow
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "3"
  poolAffinityTopologyLabel: |
    disk: slow
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-3-replica-fast
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "3"
  poolAffinityTopologyLabel: |
    disk: fast
provisioner: io.openebs.csi-mayastor
