apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - start: "192.168.10.160"
      stop: "192.168.10.170"
    - start: "2a01:cb0c:81d1:a8fb::1160"
      stop: "2a01:cb0c:81d1:a8fb::1170"