apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vm1
  namespace: external-dns
spec:
  endpoints:
  - dnsName: vm1.k8s.oodev.io
    recordTTL: 180
    recordType: A
    targets:
    - 10.60.128.205
