apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gandi-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB3LtcS4diDXm5McPK3XTTBkESlcYy2afpziS4uttkGVTeWD0J5bYJFe0q+0buCmR5wgjE4BW+NUFXdOLUuV0MUVfDLG67fClBlB9W6KjIqA0mjVad8OcShVQQDyNsHJycPptl/vEnYbx1IvI6Qpf/zVS1av05scebURmCvfZVzUKgUqDn/jPlWJzXmEUsKQLMPDxWUHHS8jbZ3PiMqFP3ityeDOSGF+SPaoTKPaiaZsvpvqHijF1V1VUQPMVEwWaOgOnbm0DrozLMXZ61mDuSIqligydKMeYgDrIb9XHh0aMCzF0t/zXcoeU6lH+XA69JhmCFwC2pt92vewPnPYYtZ4kP1a2Fn6dQOnSGgk/iQQCjmDY7S0QZpTNLB5X8hzZrtD8APJOmmLtj15/KYZ4JAl9erhbosZ3SIPzGQgTMO4aBLPd4MBSiP4RUZRWspRV6pObG9kZlXTOrxvWvHAMUwTB3X+B/zaYOmeZorqbJ9Rm0hHmOy3fRgUoBwTAf01RNJ+4t3jtKMZ5CHGJhazsoaxoMPop+innxUc5kqc1cW6lssVC7KhDZkB0FdSWxp98GnC+e9Laxv+0QE6/hOSEuF9RY3oaRTKtDXQp7YGli2Ai/Cuqi+FElnea8psKTZ+BMA1IbMHWdZZslTtgsoSDpgbERSyWgrj9/oxdf/bGdwJsUiWjukqtPMeQV2e4kjF3jP7F3gk5Nt6tLoHjiGhPrW0jrd/vejy9c=
  template:
    metadata:
      creationTimestamp: null
      name: gandi-credentials
      namespace: cert-manager
