apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-values
  namespace: nfs-subdir
data:
  values.yaml: |-
    nfs:
      server: diskstation.home
      path: /volume1/K8s
      mountOptions:
        - nfsvers=4