apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-values
  namespace: nfs-subdir
data:
  values.yaml: |-
    nfs:
      server: truenas
      path: /mnt/pool1/k8s
      mountOptions:
        - nfsvers=4