---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  # annotations:
  #   kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 58.4.0
  interval: 5m

  values:
    alertmanager:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.home
        path: "/"
    grafana:
      # normalement ingress
      # mais ici juste pour tester avec un service LB et DNSEndpoint
      service:
        enabled: true
        type: LoadBalancer

  
