---
apiVersion: v1
kind: Service
metadata:
  name: opnsense
  namespace: monitoring
  labels:
    app: opnsense
spec:    
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: opnsense
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.10.1
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
