apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opnsense
  namespace: monitoring
  labels:
    app: opnsense
    release: prometheus
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: opnsense
  namespaceSelector:
    matchNames:
      - monitoring
