apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-web
  namespace: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets-web
      version: 3.1.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-web
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: sealed-secrets-web

  values:
    ingress:
      enabled: true
      hosts:
        - host: sealedsecrets.home
          paths:
            - path: /
              pathType: Prefix
