---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
      version: 0.16.2
  interval: 15m
  timeout: 5m

  values:
    gfd:
      enabled: true
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: "none"
            failOnInitError: true
            nvidiaDriverRoot: "/"
            plugin:
              passDeviceSpecs: false
              deviceListStrategy: "envvar"
              deviceIDStrategy: "uuid"
