apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: etcd
spec:
  chart:
    spec:
      chart: etcd
      version: 10.0.9
      sourceRef:
        kind: HelmRepository
        name: etcd
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: etcd

  values:
    logLevel: "info"
    auth:
      rbac:
        create: false
