apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: showcases
spec:
  chart:
    spec:
      chart: podinfo
      version: 6.7.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: podinfo
  
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: podinfo.k8s
      hosts:
        - host: podinfo.k8s
          paths:
            - path: /
              pathType: Prefix
              pathType: ImplementationSpecific
