apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      version: 4.8.1
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: falco
  valuesFrom:
  - kind: ConfigMap
    name: falco-values
    valuesKey: values.yaml