apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent
  namespace: kube-system
spec:
  chart:
    spec:
      chart: fluentd
      version: 0.5.2
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: fluent
  valuesFrom:
  - kind: ConfigMap
    name: fluent-values
    valuesKey: values.yaml